---

- name: install the 'Development tools' package group
  package: 
    name: "@Development tools"
    state: present
  when:  ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  become: yes

- name: Install the 'build-essential' meta package
  package: 
    name: "build-essential" 
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes

- name: Install net-tools
  package: 
    name: net-tools 
    state: present
  become: yes
  become_method: sudo

- name: Install OpenSSL
  package: 
    name: openssl 
    state: present
  become: yes
  become_method: sudo

- name: Acquire code-server
  unarchive:
    src: https://github.com/cdr/code-server/releases/download/{{ coder_version }}/code-server{{ coder_version }}-linux-x86_64.tar.gz
    dest: /tmp/
    remote_src: yes
  become: yes
  become_method: sudo

- name: set code-server permission
  command: chdir=/tmp/code-server{{ coder_version }}-linux-x86_64 chmod a+x ./code-server
  become: yes
  become_method: sudo

- name: Move code-server to /user/bin
  command: chdir=/tmp/code-server{{ coder_version }}-linux-x86_64 mv ./code-server /usr/bin
  become: yes
  become_method: sudo

- name: Create coder service
  template:
    src: coder.service.j2
    dest: /etc/systemd/system/coder.service
    mode: 0644
  notify:
    - reload systemd

- name: Creates work directory
  file:
    path: "{{coder_workdir}}"
    state: directory
    recurse: yes

- name: Start coder service
  service:
    name: coder.service
    state: started
    enabled: yes