---

- name: Create two hard links
  file:
    src: /usr/bin/python2.7
    dest: /usr/bin/python
    state: link

- name: install pip
  yum:
    name: python-pip

- name: install docker-compose stuff with pip
  pip:
    name: "{{ pip_items }}"

- name: get docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    mode: 0755
    sha256sum: "{{ docker_compose_sha256sum }}"

